"""
Export Handler - Output payload templates in various formats
"""

import json
import csv
from pathlib import Path


class ExportHandler:
    """Handle exporting payloads to various formats"""
    
    def export(self, payloads, output_path, format_type='json'):
        """
        Export payloads to file
        
        Args:
            payloads (list): List of payload dictionaries
            output_path (str): Output file path
            format_type (str): Format type (json, txt, csv)
        """
        if format_type == 'json':
            self._export_json(payloads, output_path)
        elif format_type == 'txt':
            self._export_txt(payloads, output_path)
        elif format_type == 'csv':
            self._export_csv(payloads, output_path)
        else:
            raise ValueError(f"Unsupported format: {format_type}")
    
    def _export_json(self, payloads, output_path):
        """Export as JSON with metadata"""
        output = {
            'metadata': {
                'tool': 'Payload Generation Framework',
                'version': '1.0',
                'warning': 'Educational use only. Unauthorized use is prohibited.',
                'count': len(payloads)
            },
            'payloads': payloads
        }
        
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(output, f, indent=2, ensure_ascii=False)
    
    def _export_txt(self, payloads, output_path):
        """Export as plain text catalog"""
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("="*80 + "\n")
            f.write("PAYLOAD GENERATION FRAMEWORK - EDUCATIONAL CATALOG\n")
            f.write("WARNING: For authorized testing only\n")
            f.write("="*80 + "\n\n")
            
            for idx, payload in enumerate(payloads, 1):
                f.write(f"[{idx}] {payload['type']}")
                if 'subtype' in payload:
                    f.write(f" - {payload['subtype']}")
                f.write("\n")
                
                f.write(f"Context: {payload.get('context', 'N/A')}\n")
                f.write(f"Description: {payload['description']}\n")
                f.write(f"Payload: {payload['payload']}\n")
                
                if 'bypass_explanation' in payload:
                    f.write(f"Bypass: {payload['bypass_explanation']}\n")
                
                if 'defensive_notes' in payload:
                    f.write(f"Defense: {payload['defensive_notes']}\n")
                
                f.write("\n" + "-"*80 + "\n\n")
    
    def _export_csv(self, payloads, output_path):
        """Export as CSV for spreadsheet analysis"""
        if not payloads:
            return
        
        # Determine all possible fields
        all_fields = set()
        for payload in payloads:
            all_fields.update(payload.keys())
        
        fieldnames = sorted(all_fields)
        
        with open(output_path, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(payloads)
    
    def export_burp_format(self, payloads, output_path):
        """
        Export in Burp Suite Intruder compatible format
        
        Creates a simple payload list that can be loaded into Burp Intruder
        """
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# Burp Suite Payload List\n")
            f.write("# Generated by Payload Framework\n")
            f.write("# Educational use only\n\n")
            
            for payload in payloads:
                f.write(payload['payload'] + "\n")
    
    def export_zap_format(self, payloads, output_path):
        """
        Export in OWASP ZAP fuzzer compatible format
        
        Creates formatted list for ZAP fuzzer
        """
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write("# OWASP ZAP Fuzzer Payloads\n")
            f.write("# Educational security testing only\n\n")
            
            for payload in payloads:
                # ZAP format: payload | category
                category = f"{payload['type']}-{payload.get('subtype', 'default')}"
                f.write(f"{payload['payload']}\t{category}\n")